baseURL = "http://localhost/"
languageCode = "en-us"
title = ""
theme = "minimal"

[[menu.main]]
url = "/"
name = "home"
weight = 1

[[menu.main]]
url = "/services/"
name = "services"
weight = 2

[[menu.main]]
url = "/clients/"
name = "portfolio"
weight = 3

[[menu.main]]
url = "/projects/"
name = "projects"
weight = 4

[[menu.main]]
url = "/posts/"
name = "blog"
weight = 5

[[menu.main]]
url = "/impressum/"
name = "impressum"
weight = 6

[params]
    author = "Andr√© Boddenberg"
    description = "<font size=\"7\" color=\"black\">boddenberg.it</font><br>CI focused IT consulting<br><br><a href=\"/services\">see our services</a>"
    githubUsername = "boddenberg-it"
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!

    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:andre@boddenberg.it"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://git.boddenberg.it/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/andre-boddenberg/"
    name = "linkedin"
    weight = 3
